# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

exports_files([
    "etc/logging.json",
    "etc/log-channels.json",
])

filegroup(
    name = "etc_configs",
    srcs = [
        "etc/log-channels.json",
        "etc/logging.json",
    ],
    visibility = ["//visibility:public"],
)
