# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
name: AutoSD - Build & Integration Test
on:
  workflow_dispatch:
  pull_request:
  release:
    types: [created]
  push:
    branches:
      - main
# Do not flood CI with unneeded previous runs in PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: ${{ github.ref_name != 'main' && !startsWith(github.ref_name, 'release/') }}
jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to upload release assets
    steps:
      - name: Clean disk space
        uses: eclipse-score/more-disk-space@v1
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
          cache-save: ${{ github.event_name == 'push' }}
      - name: Install System Packages
        run: |
          sudo apt update -y
          sudo apt install skopeo
      - name: Build Image
        run: |
          bazel build --config=autosd-x86_64 //images/autosd_x86_64:image
      - name: Load Image
        run: |
          bazel run --config=autosd-x86_64 //images/autosd_x86_64:image_load 
      - name: Check Images
        run: |
          sudo skopeo copy docker-daemon:score_showcases_autosd:latest oci-archive:images/autosd_x86_64/score_showcases_autosd.oci
          sudo chown $(id -u):$(id -u) images/autosd_x86_64/score_showcases_autosd.oci
      - name: Check OCI Layers
        run: |
          sudo docker history score_showcases_autosd:latest
          echo ---
          skopeo inspect oci-archive:images/autosd_x86_64/score_showcases_autosd.oci
      - name: Archive Showcases OCI file
        uses: actions/upload-artifact@v4
        with:
          name: score_showcases_autosd.oci
          path: images/autosd_x86_64/score_showcases_autosd.oci
  test-x86_64:
    runs-on: ubuntu-latest
    needs: build-x86_64
    defaults:
      run:
        working-directory: images/autosd_x86_64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
          cache-save: ${{ github.event_name == 'push' }}
      - name: Install System Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tree curl qemu-system
      - name: Prepare
        run: |
          mkdir -p outputs
      - name: Download Container Artifacts
        uses: actions/download-artifact@v4
        with:
          name: score_showcases_autosd.oci
          path: images/autosd_x86_64/outputs
      - name: Download AutoSD QEMU Image
        run: |
          wget -O outputs/disk.qcow2.xz \
          https://download.autosd.sig.centos.org/AutoSD-10/nightly/sample-images/auto-osbuild-qemu-autosd10-developer-ostree-x86_64-2436102657.4740ded5.qcow2.xz
          xz -d outputs/disk.qcow2.xz
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Run QEMU
        run: |
          sshcmd() {
            sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2222 root@localhost $@
          }

          scpcmd() {
            sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 2222 $@
          }

          ./scripts/run_qemu.sh outputs/disk.qcow2

          sshcmd 'cat /etc/os-release'
          
          scpcmd ./outputs/score_showcases_autosd.oci root@localhost:/tmp/score_showcases_autosd.oci
          sshcmd 'bootc switch --apply --transport=oci-archive /tmp/score_showcases_autosd.oci' || true

          for i in $(seq 1 5); do
            echo "Attempt $i/5..."
            sshcmd 'bootc status' && break
            if [ $i -eq 5 ]; then
              echo 'Reboot did not work'
              exit 1
            fi 
            sleep 2
          done

          sshcmd 'stat /showcases'
          sshcmd 'podman ps'
          sshcmd 'bluechictl status'

        env:
          SSH_PASSWORD: password
